services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: concert_ticket
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  user-service:
    build: ./backend/user-service
    ports:
      - "8001:8001"
    depends_on:
      - mysql
    volumes:
      - ./backend/user-service:/app

  booking-service:
    build: ./backend/booking-service
    ports:
      - "8002:8002"
    depends_on:
      - mysql
    volumes:
      - ./backend/booking-service:/app

  payment-service:
    build: ./backend/payment-service
    ports:
      - "8003:8003"
    depends_on:
      - mysql
    volumes:
      - ./backend/payment-service:/app

  frontend:
    build: ./frontend/concert-ticket-app
    ports:
      # - "3000:80"
      - "3000:3000"
    depends_on:
      - user-service
      - booking-service
      - payment-service
    volumes:
      - ./frontend/concert-ticket-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  db_data:
